// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: people_job.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeopleJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PeopleId   string  `protobuf:"bytes,2,opt,name=PeopleId,proto3" json:"PeopleId,omitempty"`
	PeopleSlut string  `protobuf:"bytes,3,opt,name=PeopleSlut,proto3" json:"PeopleSlut,omitempty"`
	PeopleName string  `protobuf:"bytes,4,opt,name=PeopleName,proto3" json:"PeopleName,omitempty"`
	JobId      string  `protobuf:"bytes,5,opt,name=JobId,proto3" json:"JobId,omitempty"`
	JobName    string  `protobuf:"bytes,6,opt,name=JobName,proto3" json:"JobName,omitempty"`
	JobRanking string  `protobuf:"bytes,7,opt,name=JobRanking,proto3" json:"JobRanking,omitempty"`
	Salary     float64 `protobuf:"fixed64,8,opt,name=Salary,proto3" json:"Salary,omitempty"`
	Active     bool    `protobuf:"varint,9,opt,name=Active,proto3" json:"Active,omitempty"`
}

func (x *PeopleJob) Reset() {
	*x = PeopleJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_people_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeopleJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeopleJob) ProtoMessage() {}

func (x *PeopleJob) ProtoReflect() protoreflect.Message {
	mi := &file_people_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeopleJob.ProtoReflect.Descriptor instead.
func (*PeopleJob) Descriptor() ([]byte, []int) {
	return file_people_job_proto_rawDescGZIP(), []int{0}
}

func (x *PeopleJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeopleJob) GetPeopleId() string {
	if x != nil {
		return x.PeopleId
	}
	return ""
}

func (x *PeopleJob) GetPeopleSlut() string {
	if x != nil {
		return x.PeopleSlut
	}
	return ""
}

func (x *PeopleJob) GetPeopleName() string {
	if x != nil {
		return x.PeopleName
	}
	return ""
}

func (x *PeopleJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PeopleJob) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *PeopleJob) GetJobRanking() string {
	if x != nil {
		return x.JobRanking
	}
	return ""
}

func (x *PeopleJob) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *PeopleJob) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type ListPeopleJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Salary float64 `protobuf:"fixed64,1,opt,name=salary,proto3" json:"salary,omitempty"`
	Active bool    `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *ListPeopleJobRequest) Reset() {
	*x = ListPeopleJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_people_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPeopleJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeopleJobRequest) ProtoMessage() {}

func (x *ListPeopleJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_people_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeopleJobRequest.ProtoReflect.Descriptor instead.
func (*ListPeopleJobRequest) Descriptor() ([]byte, []int) {
	return file_people_job_proto_rawDescGZIP(), []int{1}
}

func (x *ListPeopleJobRequest) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *ListPeopleJobRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type ListPeopleJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeopleJobs []*PeopleJob `protobuf:"bytes,1,rep,name=people_jobs,json=peopleJobs,proto3" json:"people_jobs,omitempty"`
}

func (x *ListPeopleJobResponse) Reset() {
	*x = ListPeopleJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_people_job_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPeopleJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeopleJobResponse) ProtoMessage() {}

func (x *ListPeopleJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_people_job_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeopleJobResponse.ProtoReflect.Descriptor instead.
func (*ListPeopleJobResponse) Descriptor() ([]byte, []int) {
	return file_people_job_proto_rawDescGZIP(), []int{2}
}

func (x *ListPeopleJobResponse) GetPeopleJobs() []*PeopleJob {
	if x != nil {
		return x.PeopleJobs
	}
	return nil
}

var File_people_job_proto protoreflect.FileDescriptor

var file_people_job_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x5f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0xf7, 0x01, 0x0a,
	0x09, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x65,
	0x6f, 0x70, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x65,
	0x6f, 0x70, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65,
	0x53, 0x6c, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x65, 0x6f, 0x70,
	0x6c, 0x65, 0x53, 0x6c, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x65, 0x6f, 0x70,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4a,
	0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4a, 0x6f, 0x62, 0x52, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4a, 0x6f, 0x62, 0x52,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x46, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65,
	0x6f, 0x70, 0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x4d,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x70, 0x65, 0x6f, 0x70, 0x6c,
	0x65, 0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4a, 0x6f,
	0x62, 0x52, 0x0a, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x32, 0x9d, 0x01,
	0x0a, 0x0c, 0x46, 0x50, 0x54, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x3b,
	0x0a, 0x0f, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4a, 0x6f,
	0x62, 0x12, 0x13, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x65, 0x6f,
	0x70, 0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x1a, 0x13, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e,
	0x67, 0x2e, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x50, 0x0a, 0x0d, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x1e, 0x2e, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x6f, 0x70,
	0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x6f, 0x70,
	0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a,
	0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_people_job_proto_rawDescOnce sync.Once
	file_people_job_proto_rawDescData = file_people_job_proto_rawDesc
)

func file_people_job_proto_rawDescGZIP() []byte {
	file_people_job_proto_rawDescOnce.Do(func() {
		file_people_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_people_job_proto_rawDescData)
	})
	return file_people_job_proto_rawDescData
}

var file_people_job_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_people_job_proto_goTypes = []interface{}{
	(*PeopleJob)(nil),             // 0: training.PeopleJob
	(*ListPeopleJobRequest)(nil),  // 1: training.ListPeopleJobRequest
	(*ListPeopleJobResponse)(nil), // 2: training.ListPeopleJobResponse
}
var file_people_job_proto_depIdxs = []int32{
	0, // 0: training.ListPeopleJobResponse.people_jobs:type_name -> training.PeopleJob
	0, // 1: training.FPTPeopleJob.AssignPeopleJob:input_type -> training.PeopleJob
	1, // 2: training.FPTPeopleJob.ListPeopleJob:input_type -> training.ListPeopleJobRequest
	0, // 3: training.FPTPeopleJob.AssignPeopleJob:output_type -> training.PeopleJob
	2, // 4: training.FPTPeopleJob.ListPeopleJob:output_type -> training.ListPeopleJobResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_people_job_proto_init() }
func file_people_job_proto_init() {
	if File_people_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_people_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeopleJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_people_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPeopleJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_people_job_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPeopleJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_people_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_people_job_proto_goTypes,
		DependencyIndexes: file_people_job_proto_depIdxs,
		MessageInfos:      file_people_job_proto_msgTypes,
	}.Build()
	File_people_job_proto = out.File
	file_people_job_proto_rawDesc = nil
	file_people_job_proto_goTypes = nil
	file_people_job_proto_depIdxs = nil
}
